POST http://127.0.0.1:7071/api/TallyHookVchd HTTP/1.1
Content-Type: application/json
{
    "eventId": "e733895f-ed7b-4b62-b664-67608a01d389",
    "eventType": "FORM_RESPONSE",
    "createdAt": "2024-10-25T20:55:35.994Z",
    "data": {
        "responseId": "K4Eeo8",
        "submissionId": "K4Eeo8",
        "respondentId": "JePgjY",
        "formId": "3EbPDN",
        "formName": "Vagon depolardan vagon yig'uv sexi bo'yicha kunlik hisobot",
        "createdAt": "2024-10-25T20:55:35.000Z",
        "fields": [
            {
                "key": "question_G6aeBO",
                "label": "Korxona nomi",
                "type": "INPUT_TEXT",
                "value": "vchd-4"
            },
            {
                "key": "question_L9BDMJ",
                "label": "Nechta yuk vagoni ta'mirga olindi",
                "type": "INPUT_TEXT",
                "value": "15"
            },
            {
                "key": "question_prXePP",
                "label": "Ta'mirga olinganlardan nechtasi DR",
                "type": "INPUT_TEXT",
                "value": "5"
            },
            {
                "key": "question_1XzW2b",
                "label": "Ta'mirga olinganlardan nechtasi KR",
                "type": "INPUT_TEXT",
                "value": "5"
            },
            {
                "key": "question_MXl1d8",
                "label": "Ta'mirga olinganlardan nechtasi KRP",
                "type": "INPUT_TEXT",
                "value": "5"
            },
            {
                "key": "question_Jqb1kX",
                "label": "Nechta yuk vagoni ta'mirlandi",
                "type": "INPUT_TEXT",
                "value": "12"
            },
            {
                "key": "question_gaXbNJ",
                "label": "Ta'mirlanganlardan nechtasi DR",
                "type": "INPUT_TEXT",
                "value": "4"
            },
            {
                "key": "question_yMrXqd",
                "label": "Ta'mirlanganlardan nechtasi KR",
                "type": "INPUT_TEXT",
                "value": "4"
            },
            {
                "key": "question_XLd5Bz",
                "label": "Ta'mirlanganlardan nechtasi KRP",
                "type": "INPUT_TEXT",
                "value": "4"
            },
            {
                "key": "question_8qVNpr",
                "label": "Qo'shimcha izoh",
                "type": "TEXTAREA",
                "value": "machi"
            }
        ]
    }
}